FROM ubuntu:14.04
LABEL maintainer "laaksonen.heikki.j@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/local/snippy
COPY LICENSE .
COPY README.rst .
COPY Makefile .
COPY requirements.txt .
COPY runner .
COPY setup.py .
COPY tox.ini .
COPY snippy/ snippy/
COPY tests/ tests/

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    gcc \
    git \
    libpq-dev \
    make \
    pkg-config \
    python3.4 \
    vim \
    && apt-get autoremove \
    && apt-get clean

ADD https://raw.githubusercontent.com/pypa/pip/5d927de5cdc7c05b1afbdd78ae0d1b127c04d9d0/contrib/get-pip.py /root/get-pip.py
RUN python3.4 /root/get-pip.py
RUN pip install pytest==3.3.1 && \
    apt-get install -y gdb python-dbg && \
    pip install -e .[test] && \
    pip install -r requirements.txt
RUN python3.4 -m pytest ./tests/test_*.py --cov snippy; exit 0

ENTRYPOINT ["tail", "-f", "/dev/null"]
