version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: "."
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
