dist: xenial
language: python
cache: pip

stages:
  - "test Linux"
  - "test macOS"

services:
  - postgresql

install:
  - "python -m pip install codecov"
  - "make upgrade-wheel"
  - "make install-tests"

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then psql -c 'create database travis_ci_test;' -U postgres; fi

jobs:
  include:
    - stage: "test Linux"
      python: "2.7"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "3.4"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "3.5"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "3.6"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "3.7"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "3.8-dev"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "pypy"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"
    - stage: "test Linux"
      python: "pypy3"
      script:
        - "make test"
        - "make test-postgresql"
        - "make test-in-memory"

    - stage: "test macOS"
      os: osx
      osx_image: xcode10
      language: generic
      script:
        - "make test"
        - "make test-in-memory"

after_success:
  - codecov
